//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 19/10/17 20:06:22
namespace NorthwindModel
{
    public partial class NorthwindEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new NorthwindEntities object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public NorthwindEntities(global::System.Uri serviceRoot) :
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }

        partial void OnContextCreated();

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Employee> Employees
        {
            get
            {
                if ((this._Employees == null))
                {
                    this._Employees = base.CreateQuery<Employee>("Employees");
                }
                return this._Employees;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Employee> _Employees;

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToEmployees(Employee employee)
        {
            base.AddObject("Employees", employee);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"NorthwindModel\" xmlns=\"http://schemas.microsoft.com/ado/2008/09/edm\">" +
                "<EntityType Name=\"Category\"><Key><PropertyRef Name=\"CategoryID\" /></Key><Propert" +
                "y Name=\"CategoryID\" Type=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"" +
                "Identity\" xmlns:p6=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" /><" +
                "Property Name=\"CategoryName\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"15\" F" +
                "ixedLength=\"false\" Unicode=\"true\" /><Property Name=\"Description\" Type=\"Edm.Strin" +
                "g\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"Picture\"" +
                " Type=\"Edm.Binary\" MaxLength=\"Max\" FixedLength=\"false\" /><NavigationProperty Nam" +
                "e=\"Products\" Relationship=\"NorthwindModel.FK_Products_Categories\" ToRole=\"Produc" +
                "ts\" FromRole=\"Categories\" /></EntityType><EntityType Name=\"CustomerDemographic\">" +
                "<Key><PropertyRef Name=\"CustomerTypeID\" /></Key><Property Name=\"CustomerTypeID\" " +
                "Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"10\" FixedLength=\"true\" Unicode=\"tr" +
                "ue\" /><Property Name=\"CustomerDesc\" Type=\"Edm.String\" MaxLength=\"Max\" FixedLengt" +
                "h=\"false\" Unicode=\"true\" /><NavigationProperty Name=\"Customers\" Relationship=\"No" +
                "rthwindModel.CustomerCustomerDemo\" ToRole=\"Customers\" FromRole=\"CustomerDemograp" +
                "hics\" /></EntityType><EntityType Name=\"Customer\"><Key><PropertyRef Name=\"Custome" +
                "rID\" /></Key><Property Name=\"CustomerID\" Type=\"Edm.String\" Nullable=\"false\" MaxL" +
                "ength=\"5\" FixedLength=\"true\" Unicode=\"true\" /><Property Name=\"CompanyName\" Type=" +
                "\"Edm.String\" Nullable=\"false\" MaxLength=\"40\" FixedLength=\"false\" Unicode=\"true\" " +
                "/><Property Name=\"ContactName\" Type=\"Edm.String\" MaxLength=\"30\" FixedLength=\"fal" +
                "se\" Unicode=\"true\" /><Property Name=\"ContactTitle\" Type=\"Edm.String\" MaxLength=\"" +
                "30\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"Address\" Type=\"Edm.Stri" +
                "ng\" MaxLength=\"60\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"City\" Ty" +
                "pe=\"Edm.String\" MaxLength=\"15\" FixedLength=\"false\" Unicode=\"true\" /><Property Na" +
                "me=\"Region\" Type=\"Edm.String\" MaxLength=\"15\" FixedLength=\"false\" Unicode=\"true\" " +
                "/><Property Name=\"PostalCode\" Type=\"Edm.String\" MaxLength=\"10\" FixedLength=\"fals" +
                "e\" Unicode=\"true\" /><Property Name=\"Country\" Type=\"Edm.String\" MaxLength=\"15\" Fi" +
                "xedLength=\"false\" Unicode=\"true\" /><Property Name=\"Phone\" Type=\"Edm.String\" MaxL" +
                "ength=\"24\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"Fax\" Type=\"Edm.S" +
                "tring\" MaxLength=\"24\" FixedLength=\"false\" Unicode=\"true\" /><NavigationProperty N" +
                "ame=\"Orders\" Relationship=\"NorthwindModel.FK_Orders_Customers\" ToRole=\"Orders\" F" +
                "romRole=\"Customers\" /><NavigationProperty Name=\"CustomerDemographics\" Relationsh" +
                "ip=\"NorthwindModel.CustomerCustomerDemo\" ToRole=\"CustomerDemographics\" FromRole=" +
                "\"Customers\" /></EntityType><EntityType Name=\"Employee\"><Key><PropertyRef Name=\"E" +
                "mployeeID\" /></Key><Property Name=\"EmployeeID\" Type=\"Edm.Int32\" Nullable=\"false\"" +
                " p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http://schemas.microsoft.com/ado/" +
                "2009/02/edm/annotation\" /><Property Name=\"LastName\" Type=\"Edm.String\" Nullable=\"" +
                "false\" MaxLength=\"20\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"First" +
                "Name\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"10\" FixedLength=\"false\" Unic" +
                "ode=\"true\" /><Property Name=\"Title\" Type=\"Edm.String\" MaxLength=\"30\" FixedLength" +
                "=\"false\" Unicode=\"true\" /><Property Name=\"TitleOfCourtesy\" Type=\"Edm.String\" Max" +
                "Length=\"25\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"BirthDate\" Type" +
                "=\"Edm.DateTime\" /><Property Name=\"HireDate\" Type=\"Edm.DateTime\" /><Property Name" +
                "=\"Address\" Type=\"Edm.String\" MaxLength=\"60\" FixedLength=\"false\" Unicode=\"true\" /" +
                "><Property Name=\"City\" Type=\"Edm.String\" MaxLength=\"15\" FixedLength=\"false\" Unic" +
                "ode=\"true\" /><Property Name=\"Region\" Type=\"Edm.String\" MaxLength=\"15\" FixedLengt" +
                "h=\"false\" Unicode=\"true\" /><Property Name=\"PostalCode\" Type=\"Edm.String\" MaxLeng" +
                "th=\"10\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"Country\" Type=\"Edm." +
                "String\" MaxLength=\"15\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"Home" +
                "Phone\" Type=\"Edm.String\" MaxLength=\"24\" FixedLength=\"false\" Unicode=\"true\" /><Pr" +
                "operty Name=\"Extension\" Type=\"Edm.String\" MaxLength=\"4\" FixedLength=\"false\" Unic" +
                "ode=\"true\" /><Property Name=\"Photo\" Type=\"Edm.Binary\" MaxLength=\"Max\" FixedLengt" +
                "h=\"false\" /><Property Name=\"Notes\" Type=\"Edm.String\" MaxLength=\"Max\" FixedLength" +
                "=\"false\" Unicode=\"true\" /><Property Name=\"ReportsTo\" Type=\"Edm.Int32\" /><Propert" +
                "y Name=\"PhotoPath\" Type=\"Edm.String\" MaxLength=\"255\" FixedLength=\"false\" Unicode" +
                "=\"true\" /><NavigationProperty Name=\"Employees1\" Relationship=\"NorthwindModel.FK_" +
                "Employees_Employees\" ToRole=\"Employees1\" FromRole=\"Employees\" /><NavigationPrope" +
                "rty Name=\"Employee1\" Relationship=\"NorthwindModel.FK_Employees_Employees\" ToRole" +
                "=\"Employees\" FromRole=\"Employees1\" /><NavigationProperty Name=\"Orders\" Relations" +
                "hip=\"NorthwindModel.FK_Orders_Employees\" ToRole=\"Orders\" FromRole=\"Employees\" />" +
                "<NavigationProperty Name=\"Territories\" Relationship=\"NorthwindModel.EmployeeTerr" +
                "itories\" ToRole=\"Territories\" FromRole=\"Employees\" /></EntityType><EntityType Na" +
                "me=\"Order_Detail\"><Key><PropertyRef Name=\"OrderID\" /><PropertyRef Name=\"ProductI" +
                "D\" /></Key><Property Name=\"OrderID\" Type=\"Edm.Int32\" Nullable=\"false\" /><Propert" +
                "y Name=\"ProductID\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"UnitPrice" +
                "\" Type=\"Edm.Decimal\" Nullable=\"false\" Precision=\"19\" Scale=\"4\" /><Property Name=" +
                "\"Quantity\" Type=\"Edm.Int16\" Nullable=\"false\" /><Property Name=\"Discount\" Type=\"E" +
                "dm.Single\" Nullable=\"false\" /><NavigationProperty Name=\"Order\" Relationship=\"Nor" +
                "thwindModel.FK_Order_Details_Orders\" ToRole=\"Orders\" FromRole=\"Order_Details\" />" +
                "<NavigationProperty Name=\"Product\" Relationship=\"NorthwindModel.FK_Order_Details" +
                "_Products\" ToRole=\"Products\" FromRole=\"Order_Details\" /></EntityType><EntityType" +
                " Name=\"Order\"><Key><PropertyRef Name=\"OrderID\" /></Key><Property Name=\"OrderID\" " +
                "Type=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"" +
                "http://schemas.microsoft.com/ado/2009/02/edm/annotation\" /><Property Name=\"Custo" +
                "merID\" Type=\"Edm.String\" MaxLength=\"5\" FixedLength=\"true\" Unicode=\"true\" /><Prop" +
                "erty Name=\"EmployeeID\" Type=\"Edm.Int32\" /><Property Name=\"OrderDate\" Type=\"Edm.D" +
                "ateTime\" /><Property Name=\"RequiredDate\" Type=\"Edm.DateTime\" /><Property Name=\"S" +
                "hippedDate\" Type=\"Edm.DateTime\" /><Property Name=\"ShipVia\" Type=\"Edm.Int32\" /><P" +
                "roperty Name=\"Freight\" Type=\"Edm.Decimal\" Precision=\"19\" Scale=\"4\" /><Property N" +
                "ame=\"ShipName\" Type=\"Edm.String\" MaxLength=\"40\" FixedLength=\"false\" Unicode=\"tru" +
                "e\" /><Property Name=\"ShipAddress\" Type=\"Edm.String\" MaxLength=\"60\" FixedLength=\"" +
                "false\" Unicode=\"true\" /><Property Name=\"ShipCity\" Type=\"Edm.String\" MaxLength=\"1" +
                "5\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"ShipRegion\" Type=\"Edm.St" +
                "ring\" MaxLength=\"15\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"ShipPo" +
                "stalCode\" Type=\"Edm.String\" MaxLength=\"10\" FixedLength=\"false\" Unicode=\"true\" />" +
                "<Property Name=\"ShipCountry\" Type=\"Edm.String\" MaxLength=\"15\" FixedLength=\"false" +
                "\" Unicode=\"true\" /><NavigationProperty Name=\"Customer\" Relationship=\"NorthwindMo" +
                "del.FK_Orders_Customers\" ToRole=\"Customers\" FromRole=\"Orders\" /><NavigationPrope" +
                "rty Name=\"Employee\" Relationship=\"NorthwindModel.FK_Orders_Employees\" ToRole=\"Em" +
                "ployees\" FromRole=\"Orders\" /><NavigationProperty Name=\"Order_Details\" Relationsh" +
                "ip=\"NorthwindModel.FK_Order_Details_Orders\" ToRole=\"Order_D";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart1 = "etails\" FromRole=\"Orders\" /><NavigationProperty Name=\"Shipper\" Relationship=\"Nort" +
                "hwindModel.FK_Orders_Shippers\" ToRole=\"Shippers\" FromRole=\"Orders\" /></EntityTyp" +
                "e><EntityType Name=\"Product\"><Key><PropertyRef Name=\"ProductID\" /></Key><Propert" +
                "y Name=\"ProductID\" Type=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"I" +
                "dentity\" xmlns:p6=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" /><P" +
                "roperty Name=\"ProductName\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"40\" Fix" +
                "edLength=\"false\" Unicode=\"true\" /><Property Name=\"SupplierID\" Type=\"Edm.Int32\" /" +
                "><Property Name=\"CategoryID\" Type=\"Edm.Int32\" /><Property Name=\"QuantityPerUnit\"" +
                " Type=\"Edm.String\" MaxLength=\"20\" FixedLength=\"false\" Unicode=\"true\" /><Property" +
                " Name=\"UnitPrice\" Type=\"Edm.Decimal\" Precision=\"19\" Scale=\"4\" /><Property Name=\"" +
                "UnitsInStock\" Type=\"Edm.Int16\" /><Property Name=\"UnitsOnOrder\" Type=\"Edm.Int16\" " +
                "/><Property Name=\"ReorderLevel\" Type=\"Edm.Int16\" /><Property Name=\"Discontinued\"" +
                " Type=\"Edm.Boolean\" Nullable=\"false\" /><NavigationProperty Name=\"Category\" Relat" +
                "ionship=\"NorthwindModel.FK_Products_Categories\" ToRole=\"Categories\" FromRole=\"Pr" +
                "oducts\" /><NavigationProperty Name=\"Order_Details\" Relationship=\"NorthwindModel." +
                "FK_Order_Details_Products\" ToRole=\"Order_Details\" FromRole=\"Products\" /><Navigat" +
                "ionProperty Name=\"Supplier\" Relationship=\"NorthwindModel.FK_Products_Suppliers\" " +
                "ToRole=\"Suppliers\" FromRole=\"Products\" /></EntityType><EntityType Name=\"Region\">" +
                "<Key><PropertyRef Name=\"RegionID\" /></Key><Property Name=\"RegionID\" Type=\"Edm.In" +
                "t32\" Nullable=\"false\" /><Property Name=\"RegionDescription\" Type=\"Edm.String\" Nul" +
                "lable=\"false\" MaxLength=\"50\" FixedLength=\"true\" Unicode=\"true\" /><NavigationProp" +
                "erty Name=\"Territories\" Relationship=\"NorthwindModel.FK_Territories_Region\" ToRo" +
                "le=\"Territories\" FromRole=\"Region\" /></EntityType><EntityType Name=\"Shipper\"><Ke" +
                "y><PropertyRef Name=\"ShipperID\" /></Key><Property Name=\"ShipperID\" Type=\"Edm.Int" +
                "32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http://schema" +
                "s.microsoft.com/ado/2009/02/edm/annotation\" /><Property Name=\"CompanyName\" Type=" +
                "\"Edm.String\" Nullable=\"false\" MaxLength=\"40\" FixedLength=\"false\" Unicode=\"true\" " +
                "/><Property Name=\"Phone\" Type=\"Edm.String\" MaxLength=\"24\" FixedLength=\"false\" Un" +
                "icode=\"true\" /><NavigationProperty Name=\"Orders\" Relationship=\"NorthwindModel.FK" +
                "_Orders_Shippers\" ToRole=\"Orders\" FromRole=\"Shippers\" /></EntityType><EntityType" +
                " Name=\"Supplier\"><Key><PropertyRef Name=\"SupplierID\" /></Key><Property Name=\"Sup" +
                "plierID\" Type=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" x" +
                "mlns:p6=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" /><Property Na" +
                "me=\"CompanyName\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"40\" FixedLength=\"" +
                "false\" Unicode=\"true\" /><Property Name=\"ContactName\" Type=\"Edm.String\" MaxLength" +
                "=\"30\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"ContactTitle\" Type=\"E" +
                "dm.String\" MaxLength=\"30\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"A" +
                "ddress\" Type=\"Edm.String\" MaxLength=\"60\" FixedLength=\"false\" Unicode=\"true\" /><P" +
                "roperty Name=\"City\" Type=\"Edm.String\" MaxLength=\"15\" FixedLength=\"false\" Unicode" +
                "=\"true\" /><Property Name=\"Region\" Type=\"Edm.String\" MaxLength=\"15\" FixedLength=\"" +
                "false\" Unicode=\"true\" /><Property Name=\"PostalCode\" Type=\"Edm.String\" MaxLength=" +
                "\"10\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"Country\" Type=\"Edm.Str" +
                "ing\" MaxLength=\"15\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"Phone\" " +
                "Type=\"Edm.String\" MaxLength=\"24\" FixedLength=\"false\" Unicode=\"true\" /><Property " +
                "Name=\"Fax\" Type=\"Edm.String\" MaxLength=\"24\" FixedLength=\"false\" Unicode=\"true\" /" +
                "><Property Name=\"HomePage\" Type=\"Edm.String\" MaxLength=\"Max\" FixedLength=\"false\"" +
                " Unicode=\"true\" /><NavigationProperty Name=\"Products\" Relationship=\"NorthwindMod" +
                "el.FK_Products_Suppliers\" ToRole=\"Products\" FromRole=\"Suppliers\" /></EntityType>" +
                "<EntityType Name=\"Territory\"><Key><PropertyRef Name=\"TerritoryID\" /></Key><Prope" +
                "rty Name=\"TerritoryID\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"20\" FixedLe" +
                "ngth=\"false\" Unicode=\"true\" /><Property Name=\"TerritoryDescription\" Type=\"Edm.St" +
                "ring\" Nullable=\"false\" MaxLength=\"50\" FixedLength=\"true\" Unicode=\"true\" /><Prope" +
                "rty Name=\"RegionID\" Type=\"Edm.Int32\" Nullable=\"false\" /><NavigationProperty Name" +
                "=\"Region\" Relationship=\"NorthwindModel.FK_Territories_Region\" ToRole=\"Region\" Fr" +
                "omRole=\"Territories\" /><NavigationProperty Name=\"Employees\" Relationship=\"Northw" +
                "indModel.EmployeeTerritories\" ToRole=\"Employees\" FromRole=\"Territories\" /></Enti" +
                "tyType><EntityType Name=\"Alphabetical_list_of_product\"><Key><PropertyRef Name=\"C" +
                "ategoryName\" /><PropertyRef Name=\"Discontinued\" /><PropertyRef Name=\"ProductID\" " +
                "/><PropertyRef Name=\"ProductName\" /></Key><Property Name=\"ProductID\" Type=\"Edm.I" +
                "nt32\" Nullable=\"false\" /><Property Name=\"ProductName\" Type=\"Edm.String\" Nullable" +
                "=\"false\" MaxLength=\"40\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"Sup" +
                "plierID\" Type=\"Edm.Int32\" /><Property Name=\"CategoryID\" Type=\"Edm.Int32\" /><Prop" +
                "erty Name=\"QuantityPerUnit\" Type=\"Edm.String\" MaxLength=\"20\" FixedLength=\"false\"" +
                " Unicode=\"true\" /><Property Name=\"UnitPrice\" Type=\"Edm.Decimal\" Precision=\"19\" S" +
                "cale=\"4\" /><Property Name=\"UnitsInStock\" Type=\"Edm.Int16\" /><Property Name=\"Unit" +
                "sOnOrder\" Type=\"Edm.Int16\" /><Property Name=\"ReorderLevel\" Type=\"Edm.Int16\" /><P" +
                "roperty Name=\"Discontinued\" Type=\"Edm.Boolean\" Nullable=\"false\" /><Property Name" +
                "=\"CategoryName\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"15\" FixedLength=\"f" +
                "alse\" Unicode=\"true\" /></EntityType><EntityType Name=\"Category_Sales_for_1997\"><" +
                "Key><PropertyRef Name=\"CategoryName\" /></Key><Property Name=\"CategoryName\" Type=" +
                "\"Edm.String\" Nullable=\"false\" MaxLength=\"15\" FixedLength=\"false\" Unicode=\"true\" " +
                "/><Property Name=\"CategorySales\" Type=\"Edm.Decimal\" Precision=\"19\" Scale=\"4\" /><" +
                "/EntityType><EntityType Name=\"Current_Product_List\"><Key><PropertyRef Name=\"Prod" +
                "uctID\" /><PropertyRef Name=\"ProductName\" /></Key><Property Name=\"ProductID\" Type" +
                "=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http" +
                "://schemas.microsoft.com/ado/2009/02/edm/annotation\" /><Property Name=\"ProductNa" +
                "me\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"40\" FixedLength=\"false\" Unicod" +
                "e=\"true\" /></EntityType><EntityType Name=\"Customer_and_Suppliers_by_City\"><Key><" +
                "PropertyRef Name=\"CompanyName\" /><PropertyRef Name=\"Relationship\" /></Key><Prope" +
                "rty Name=\"City\" Type=\"Edm.String\" MaxLength=\"15\" FixedLength=\"false\" Unicode=\"tr" +
                "ue\" /><Property Name=\"CompanyName\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=" +
                "\"40\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"ContactName\" Type=\"Edm" +
                ".String\" MaxLength=\"30\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"Rel" +
                "ationship\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"9\" FixedLength=\"false\" " +
                "Unicode=\"false\" /></EntityType><EntityType Name=\"Invoice\"><Key><PropertyRef Name" +
                "=\"CustomerName\" /><PropertyRef Name=\"Discount\" /><PropertyRef Name=\"OrderID\" /><" +
                "PropertyRef Name=\"ProductID\" /><PropertyRef Name=\"ProductName\" /><PropertyRef Na" +
                "me=\"Quantity\" /><PropertyRef Name=\"Salesperson\" /><PropertyRef Name=\"ShipperName" +
                "\" /><PropertyRef Name=\"UnitPrice\" /></Key><Property Name=\"ShipName\" Type=\"Edm.St" +
                "ring\" MaxLength=\"40\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"ShipAd" +
                "dress\" Type=\"Edm.String\" MaxLength=\"60\" FixedLength=\"false\" Unicode=\"true\" /><Pr" +
                "operty Name=\"ShipCity\" Type=\"Edm.String\" MaxLength=\"15\" FixedLength=\"false\" Unic" +
                "ode=\"true\" /><Property Name=\"ShipRegion\" Type=\"Edm.String\" MaxLength=\"15\" FixedL" +
                "ength=\"false\" Unicode=\"true\" /><Property Name=\"ShipPostalCo";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart2 = "de\" Type=\"Edm.String\" MaxLength=\"10\" FixedLength=\"false\" Unicode=\"true\" /><Proper" +
                "ty Name=\"ShipCountry\" Type=\"Edm.String\" MaxLength=\"15\" FixedLength=\"false\" Unico" +
                "de=\"true\" /><Property Name=\"CustomerID\" Type=\"Edm.String\" MaxLength=\"5\" FixedLen" +
                "gth=\"true\" Unicode=\"true\" /><Property Name=\"CustomerName\" Type=\"Edm.String\" Null" +
                "able=\"false\" MaxLength=\"40\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=" +
                "\"Address\" Type=\"Edm.String\" MaxLength=\"60\" FixedLength=\"false\" Unicode=\"true\" />" +
                "<Property Name=\"City\" Type=\"Edm.String\" MaxLength=\"15\" FixedLength=\"false\" Unico" +
                "de=\"true\" /><Property Name=\"Region\" Type=\"Edm.String\" MaxLength=\"15\" FixedLength" +
                "=\"false\" Unicode=\"true\" /><Property Name=\"PostalCode\" Type=\"Edm.String\" MaxLengt" +
                "h=\"10\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"Country\" Type=\"Edm.S" +
                "tring\" MaxLength=\"15\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"Sales" +
                "person\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"31\" FixedLength=\"false\" Un" +
                "icode=\"true\" /><Property Name=\"OrderID\" Type=\"Edm.Int32\" Nullable=\"false\" /><Pro" +
                "perty Name=\"OrderDate\" Type=\"Edm.DateTime\" /><Property Name=\"RequiredDate\" Type=" +
                "\"Edm.DateTime\" /><Property Name=\"ShippedDate\" Type=\"Edm.DateTime\" /><Property Na" +
                "me=\"ShipperName\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"40\" FixedLength=\"" +
                "false\" Unicode=\"true\" /><Property Name=\"ProductID\" Type=\"Edm.Int32\" Nullable=\"fa" +
                "lse\" /><Property Name=\"ProductName\" Type=\"Edm.String\" Nullable=\"false\" MaxLength" +
                "=\"40\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"UnitPrice\" Type=\"Edm." +
                "Decimal\" Nullable=\"false\" Precision=\"19\" Scale=\"4\" /><Property Name=\"Quantity\" T" +
                "ype=\"Edm.Int16\" Nullable=\"false\" /><Property Name=\"Discount\" Type=\"Edm.Single\" N" +
                "ullable=\"false\" /><Property Name=\"ExtendedPrice\" Type=\"Edm.Decimal\" Precision=\"1" +
                "9\" Scale=\"4\" /><Property Name=\"Freight\" Type=\"Edm.Decimal\" Precision=\"19\" Scale=" +
                "\"4\" /></EntityType><EntityType Name=\"Order_Details_Extended\"><Key><PropertyRef N" +
                "ame=\"Discount\" /><PropertyRef Name=\"OrderID\" /><PropertyRef Name=\"ProductID\" /><" +
                "PropertyRef Name=\"ProductName\" /><PropertyRef Name=\"Quantity\" /><PropertyRef Nam" +
                "e=\"UnitPrice\" /></Key><Property Name=\"OrderID\" Type=\"Edm.Int32\" Nullable=\"false\"" +
                " /><Property Name=\"ProductID\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name" +
                "=\"ProductName\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"40\" FixedLength=\"fa" +
                "lse\" Unicode=\"true\" /><Property Name=\"UnitPrice\" Type=\"Edm.Decimal\" Nullable=\"fa" +
                "lse\" Precision=\"19\" Scale=\"4\" /><Property Name=\"Quantity\" Type=\"Edm.Int16\" Nulla" +
                "ble=\"false\" /><Property Name=\"Discount\" Type=\"Edm.Single\" Nullable=\"false\" /><Pr" +
                "operty Name=\"ExtendedPrice\" Type=\"Edm.Decimal\" Precision=\"19\" Scale=\"4\" /></Enti" +
                "tyType><EntityType Name=\"Order_Subtotal\"><Key><PropertyRef Name=\"OrderID\" /></Ke" +
                "y><Property Name=\"OrderID\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"S" +
                "ubtotal\" Type=\"Edm.Decimal\" Precision=\"19\" Scale=\"4\" /></EntityType><EntityType " +
                "Name=\"Orders_Qry\"><Key><PropertyRef Name=\"CompanyName\" /><PropertyRef Name=\"Orde" +
                "rID\" /></Key><Property Name=\"OrderID\" Type=\"Edm.Int32\" Nullable=\"false\" /><Prope" +
                "rty Name=\"CustomerID\" Type=\"Edm.String\" MaxLength=\"5\" FixedLength=\"true\" Unicode" +
                "=\"true\" /><Property Name=\"EmployeeID\" Type=\"Edm.Int32\" /><Property Name=\"OrderDa" +
                "te\" Type=\"Edm.DateTime\" /><Property Name=\"RequiredDate\" Type=\"Edm.DateTime\" /><P" +
                "roperty Name=\"ShippedDate\" Type=\"Edm.DateTime\" /><Property Name=\"ShipVia\" Type=\"" +
                "Edm.Int32\" /><Property Name=\"Freight\" Type=\"Edm.Decimal\" Precision=\"19\" Scale=\"4" +
                "\" /><Property Name=\"ShipName\" Type=\"Edm.String\" MaxLength=\"40\" FixedLength=\"fals" +
                "e\" Unicode=\"true\" /><Property Name=\"ShipAddress\" Type=\"Edm.String\" MaxLength=\"60" +
                "\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"ShipCity\" Type=\"Edm.Strin" +
                "g\" MaxLength=\"15\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"ShipRegio" +
                "n\" Type=\"Edm.String\" MaxLength=\"15\" FixedLength=\"false\" Unicode=\"true\" /><Proper" +
                "ty Name=\"ShipPostalCode\" Type=\"Edm.String\" MaxLength=\"10\" FixedLength=\"false\" Un" +
                "icode=\"true\" /><Property Name=\"ShipCountry\" Type=\"Edm.String\" MaxLength=\"15\" Fix" +
                "edLength=\"false\" Unicode=\"true\" /><Property Name=\"CompanyName\" Type=\"Edm.String\"" +
                " Nullable=\"false\" MaxLength=\"40\" FixedLength=\"false\" Unicode=\"true\" /><Property " +
                "Name=\"Address\" Type=\"Edm.String\" MaxLength=\"60\" FixedLength=\"false\" Unicode=\"tru" +
                "e\" /><Property Name=\"City\" Type=\"Edm.String\" MaxLength=\"15\" FixedLength=\"false\" " +
                "Unicode=\"true\" /><Property Name=\"Region\" Type=\"Edm.String\" MaxLength=\"15\" FixedL" +
                "ength=\"false\" Unicode=\"true\" /><Property Name=\"PostalCode\" Type=\"Edm.String\" Max" +
                "Length=\"10\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"Country\" Type=\"" +
                "Edm.String\" MaxLength=\"15\" FixedLength=\"false\" Unicode=\"true\" /></EntityType><En" +
                "tityType Name=\"Product_Sales_for_1997\"><Key><PropertyRef Name=\"CategoryName\" /><" +
                "PropertyRef Name=\"ProductName\" /></Key><Property Name=\"CategoryName\" Type=\"Edm.S" +
                "tring\" Nullable=\"false\" MaxLength=\"15\" FixedLength=\"false\" Unicode=\"true\" /><Pro" +
                "perty Name=\"ProductName\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"40\" Fixed" +
                "Length=\"false\" Unicode=\"true\" /><Property Name=\"ProductSales\" Type=\"Edm.Decimal\"" +
                " Precision=\"19\" Scale=\"4\" /></EntityType><EntityType Name=\"Products_Above_Averag" +
                "e_Price\"><Key><PropertyRef Name=\"ProductName\" /></Key><Property Name=\"ProductNam" +
                "e\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"40\" FixedLength=\"false\" Unicode" +
                "=\"true\" /><Property Name=\"UnitPrice\" Type=\"Edm.Decimal\" Precision=\"19\" Scale=\"4\"" +
                " /></EntityType><EntityType Name=\"Products_by_Category\"><Key><PropertyRef Name=\"" +
                "CategoryName\" /><PropertyRef Name=\"Discontinued\" /><PropertyRef Name=\"ProductNam" +
                "e\" /></Key><Property Name=\"CategoryName\" Type=\"Edm.String\" Nullable=\"false\" MaxL" +
                "ength=\"15\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"ProductName\" Typ" +
                "e=\"Edm.String\" Nullable=\"false\" MaxLength=\"40\" FixedLength=\"false\" Unicode=\"true" +
                "\" /><Property Name=\"QuantityPerUnit\" Type=\"Edm.String\" MaxLength=\"20\" FixedLengt" +
                "h=\"false\" Unicode=\"true\" /><Property Name=\"UnitsInStock\" Type=\"Edm.Int16\" /><Pro" +
                "perty Name=\"Discontinued\" Type=\"Edm.Boolean\" Nullable=\"false\" /></EntityType><En" +
                "tityType Name=\"Sales_by_Category\"><Key><PropertyRef Name=\"CategoryID\" /><Propert" +
                "yRef Name=\"CategoryName\" /><PropertyRef Name=\"ProductName\" /></Key><Property Nam" +
                "e=\"CategoryID\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"CategoryName\"" +
                " Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"15\" FixedLength=\"false\" Unicode=\"" +
                "true\" /><Property Name=\"ProductName\" Type=\"Edm.String\" Nullable=\"false\" MaxLengt" +
                "h=\"40\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"ProductSales\" Type=\"" +
                "Edm.Decimal\" Precision=\"19\" Scale=\"4\" /></EntityType><EntityType Name=\"Sales_Tot" +
                "als_by_Amount\"><Key><PropertyRef Name=\"CompanyName\" /><PropertyRef Name=\"OrderID" +
                "\" /></Key><Property Name=\"SaleAmount\" Type=\"Edm.Decimal\" Precision=\"19\" Scale=\"4" +
                "\" /><Property Name=\"OrderID\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=" +
                "\"CompanyName\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"40\" FixedLength=\"fal" +
                "se\" Unicode=\"true\" /><Property Name=\"ShippedDate\" Type=\"Edm.DateTime\" /></Entity" +
                "Type><EntityType Name=\"Summary_of_Sales_by_Quarter\"><Key><PropertyRef Name=\"Orde" +
                "rID\" /></Key><Property Name=\"ShippedDate\" Type=\"Edm.DateTime\" /><Property Name=\"" +
                "OrderID\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Subtotal\" Type=\"Edm" +
                ".Decimal\" Precision=\"19\" Scale=\"4\" /></EntityType><EntityType Name=\"Summary_of_S" +
                "ales_by_Year\"><Key><PropertyRef Name=\"OrderID\" /></Key><Property Name=\"ShippedDa" +
                "te\" Type=\"Edm.DateTime\" /><Property Name=\"OrderID\" Type=\"Edm.Int32\" Nullable=\"fa" +
                "lse\" /><Property Name=\"Subtotal\" Type=\"Edm.Decimal\" Precisi";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart3 = "on=\"19\" Scale=\"4\" /></EntityType><Association Name=\"FK_Products_Categories\"><End " +
                "Type=\"NorthwindModel.Category\" Role=\"Categories\" Multiplicity=\"0..1\" /><End Type" +
                "=\"NorthwindModel.Product\" Role=\"Products\" Multiplicity=\"*\" /><ReferentialConstra" +
                "int><Principal Role=\"Categories\"><PropertyRef Name=\"CategoryID\" /></Principal><D" +
                "ependent Role=\"Products\"><PropertyRef Name=\"CategoryID\" /></Dependent></Referent" +
                "ialConstraint></Association><Association Name=\"CustomerCustomerDemo\"><End Type=\"" +
                "NorthwindModel.Customer\" Role=\"Customers\" Multiplicity=\"*\" /><End Type=\"Northwin" +
                "dModel.CustomerDemographic\" Role=\"CustomerDemographics\" Multiplicity=\"*\" /></Ass" +
                "ociation><Association Name=\"FK_Orders_Customers\"><End Type=\"NorthwindModel.Custo" +
                "mer\" Role=\"Customers\" Multiplicity=\"0..1\" /><End Type=\"NorthwindModel.Order\" Rol" +
                "e=\"Orders\" Multiplicity=\"*\" /><ReferentialConstraint><Principal Role=\"Customers\"" +
                "><PropertyRef Name=\"CustomerID\" /></Principal><Dependent Role=\"Orders\"><Property" +
                "Ref Name=\"CustomerID\" /></Dependent></ReferentialConstraint></Association><Assoc" +
                "iation Name=\"FK_Employees_Employees\"><End Type=\"NorthwindModel.Employee\" Role=\"E" +
                "mployees\" Multiplicity=\"0..1\" /><End Type=\"NorthwindModel.Employee\" Role=\"Employ" +
                "ees1\" Multiplicity=\"*\" /><ReferentialConstraint><Principal Role=\"Employees\"><Pro" +
                "pertyRef Name=\"EmployeeID\" /></Principal><Dependent Role=\"Employees1\"><PropertyR" +
                "ef Name=\"ReportsTo\" /></Dependent></ReferentialConstraint></Association><Associa" +
                "tion Name=\"FK_Orders_Employees\"><End Type=\"NorthwindModel.Employee\" Role=\"Employ" +
                "ees\" Multiplicity=\"0..1\" /><End Type=\"NorthwindModel.Order\" Role=\"Orders\" Multip" +
                "licity=\"*\" /><ReferentialConstraint><Principal Role=\"Employees\"><PropertyRef Nam" +
                "e=\"EmployeeID\" /></Principal><Dependent Role=\"Orders\"><PropertyRef Name=\"Employe" +
                "eID\" /></Dependent></ReferentialConstraint></Association><Association Name=\"Empl" +
                "oyeeTerritories\"><End Type=\"NorthwindModel.Territory\" Role=\"Territories\" Multipl" +
                "icity=\"*\" /><End Type=\"NorthwindModel.Employee\" Role=\"Employees\" Multiplicity=\"*" +
                "\" /></Association><Association Name=\"FK_Order_Details_Orders\"><End Type=\"Northwi" +
                "ndModel.Order\" Role=\"Orders\" Multiplicity=\"1\" /><End Type=\"NorthwindModel.Order_" +
                "Detail\" Role=\"Order_Details\" Multiplicity=\"*\" /><ReferentialConstraint><Principa" +
                "l Role=\"Orders\"><PropertyRef Name=\"OrderID\" /></Principal><Dependent Role=\"Order" +
                "_Details\"><PropertyRef Name=\"OrderID\" /></Dependent></ReferentialConstraint></As" +
                "sociation><Association Name=\"FK_Order_Details_Products\"><End Type=\"NorthwindMode" +
                "l.Product\" Role=\"Products\" Multiplicity=\"1\" /><End Type=\"NorthwindModel.Order_De" +
                "tail\" Role=\"Order_Details\" Multiplicity=\"*\" /><ReferentialConstraint><Principal " +
                "Role=\"Products\"><PropertyRef Name=\"ProductID\" /></Principal><Dependent Role=\"Ord" +
                "er_Details\"><PropertyRef Name=\"ProductID\" /></Dependent></ReferentialConstraint>" +
                "</Association><Association Name=\"FK_Orders_Shippers\"><End Type=\"NorthwindModel.S" +
                "hipper\" Role=\"Shippers\" Multiplicity=\"0..1\" /><End Type=\"NorthwindModel.Order\" R" +
                "ole=\"Orders\" Multiplicity=\"*\" /><ReferentialConstraint><Principal Role=\"Shippers" +
                "\"><PropertyRef Name=\"ShipperID\" /></Principal><Dependent Role=\"Orders\"><Property" +
                "Ref Name=\"ShipVia\" /></Dependent></ReferentialConstraint></Association><Associat" +
                "ion Name=\"FK_Products_Suppliers\"><End Type=\"NorthwindModel.Supplier\" Role=\"Suppl" +
                "iers\" Multiplicity=\"0..1\" /><End Type=\"NorthwindModel.Product\" Role=\"Products\" M" +
                "ultiplicity=\"*\" /><ReferentialConstraint><Principal Role=\"Suppliers\"><PropertyRe" +
                "f Name=\"SupplierID\" /></Principal><Dependent Role=\"Products\"><PropertyRef Name=\"" +
                "SupplierID\" /></Dependent></ReferentialConstraint></Association><Association Nam" +
                "e=\"FK_Territories_Region\"><End Type=\"NorthwindModel.Region\" Role=\"Region\" Multip" +
                "licity=\"1\" /><End Type=\"NorthwindModel.Territory\" Role=\"Territories\" Multiplicit" +
                "y=\"*\" /><ReferentialConstraint><Principal Role=\"Region\"><PropertyRef Name=\"Regio" +
                "nID\" /></Principal><Dependent Role=\"Territories\"><PropertyRef Name=\"RegionID\" />" +
                "</Dependent></ReferentialConstraint></Association></Schema><Schema Namespace=\"OD" +
                "ataWebV3.Northwind.Model\" xmlns=\"http://schemas.microsoft.com/ado/2008/09/edm\"><" +
                "EntityContainer Name=\"NorthwindEntities\" m:IsDefaultEntityContainer=\"true\" p6:La" +
                "zyLoadingEnabled=\"true\" xmlns:p6=\"http://schemas.microsoft.com/ado/2009/02/edm/a" +
                "nnotation\"><EntitySet Name=\"Categories\" EntityType=\"NorthwindModel.Category\" /><" +
                "EntitySet Name=\"CustomerDemographics\" EntityType=\"NorthwindModel.CustomerDemogra" +
                "phic\" /><EntitySet Name=\"Customers\" EntityType=\"NorthwindModel.Customer\" /><Enti" +
                "tySet Name=\"Employees\" EntityType=\"NorthwindModel.Employee\" /><EntitySet Name=\"O" +
                "rder_Details\" EntityType=\"NorthwindModel.Order_Detail\" /><EntitySet Name=\"Orders" +
                "\" EntityType=\"NorthwindModel.Order\" /><EntitySet Name=\"Products\" EntityType=\"Nor" +
                "thwindModel.Product\" /><EntitySet Name=\"Regions\" EntityType=\"NorthwindModel.Regi" +
                "on\" /><EntitySet Name=\"Shippers\" EntityType=\"NorthwindModel.Shipper\" /><EntitySe" +
                "t Name=\"Suppliers\" EntityType=\"NorthwindModel.Supplier\" /><EntitySet Name=\"Terri" +
                "tories\" EntityType=\"NorthwindModel.Territory\" /><EntitySet Name=\"Alphabetical_li" +
                "st_of_products\" EntityType=\"NorthwindModel.Alphabetical_list_of_product\" /><Enti" +
                "tySet Name=\"Category_Sales_for_1997\" EntityType=\"NorthwindModel.Category_Sales_f" +
                "or_1997\" /><EntitySet Name=\"Current_Product_Lists\" EntityType=\"NorthwindModel.Cu" +
                "rrent_Product_List\" /><EntitySet Name=\"Customer_and_Suppliers_by_Cities\" EntityT" +
                "ype=\"NorthwindModel.Customer_and_Suppliers_by_City\" /><EntitySet Name=\"Invoices\"" +
                " EntityType=\"NorthwindModel.Invoice\" /><EntitySet Name=\"Order_Details_Extendeds\"" +
                " EntityType=\"NorthwindModel.Order_Details_Extended\" /><EntitySet Name=\"Order_Sub" +
                "totals\" EntityType=\"NorthwindModel.Order_Subtotal\" /><EntitySet Name=\"Orders_Qri" +
                "es\" EntityType=\"NorthwindModel.Orders_Qry\" /><EntitySet Name=\"Product_Sales_for_" +
                "1997\" EntityType=\"NorthwindModel.Product_Sales_for_1997\" /><EntitySet Name=\"Prod" +
                "ucts_Above_Average_Prices\" EntityType=\"NorthwindModel.Products_Above_Average_Pri" +
                "ce\" /><EntitySet Name=\"Products_by_Categories\" EntityType=\"NorthwindModel.Produc" +
                "ts_by_Category\" /><EntitySet Name=\"Sales_by_Categories\" EntityType=\"NorthwindMod" +
                "el.Sales_by_Category\" /><EntitySet Name=\"Sales_Totals_by_Amounts\" EntityType=\"No" +
                "rthwindModel.Sales_Totals_by_Amount\" /><EntitySet Name=\"Summary_of_Sales_by_Quar" +
                "ters\" EntityType=\"NorthwindModel.Summary_of_Sales_by_Quarter\" /><EntitySet Name=" +
                "\"Summary_of_Sales_by_Years\" EntityType=\"NorthwindModel.Summary_of_Sales_by_Year\"" +
                " /><AssociationSet Name=\"FK_Products_Categories\" Association=\"NorthwindModel.FK_" +
                "Products_Categories\"><End Role=\"Categories\" EntitySet=\"Categories\" /><End Role=\"" +
                "Products\" EntitySet=\"Products\" /></AssociationSet><AssociationSet Name=\"Customer" +
                "CustomerDemo\" Association=\"NorthwindModel.CustomerCustomerDemo\"><End Role=\"Custo" +
                "merDemographics\" EntitySet=\"CustomerDemographics\" /><End Role=\"Customers\" Entity" +
                "Set=\"Customers\" /></AssociationSet><AssociationSet Name=\"FK_Orders_Customers\" As" +
                "sociation=\"NorthwindModel.FK_Orders_Customers\"><End Role=\"Customers\" EntitySet=\"" +
                "Customers\" /><End Role=\"Orders\" EntitySet=\"Orders\" /></AssociationSet><Associati" +
                "onSet Name=\"FK_Employees_Employees\" Association=\"NorthwindModel.FK_Employees_Emp" +
                "loyees\"><End Role=\"Employees\" EntitySet=\"Employees\" /><End Role=\"Employees1\" Ent" +
                "itySet=\"Employees\" /></AssociationSet><AssociationSet Name=\"FK_Orders_Employees\"" +
                " Association=\"NorthwindModel.FK_Orders_Employees\"><End Role=\"Employees\" EntitySe" +
                "t=\"Employees\" /><End Role=\"Orders\" EntitySet=\"Orders\" /></AssociationSet><Associ" +
                "ationSet Name=\"EmployeeTerritories\" Association=\"NorthwindM";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart4 = @"odel.EmployeeTerritories""><End Role=""Employees"" EntitySet=""Employees"" /><End Role=""Territories"" EntitySet=""Territories"" /></AssociationSet><AssociationSet Name=""FK_Order_Details_Orders"" Association=""NorthwindModel.FK_Order_Details_Orders""><End Role=""Order_Details"" EntitySet=""Order_Details"" /><End Role=""Orders"" EntitySet=""Orders"" /></AssociationSet><AssociationSet Name=""FK_Order_Details_Products"" Association=""NorthwindModel.FK_Order_Details_Products""><End Role=""Order_Details"" EntitySet=""Order_Details"" /><End Role=""Products"" EntitySet=""Products"" /></AssociationSet><AssociationSet Name=""FK_Orders_Shippers"" Association=""NorthwindModel.FK_Orders_Shippers""><End Role=""Orders"" EntitySet=""Orders"" /><End Role=""Shippers"" EntitySet=""Shippers"" /></AssociationSet><AssociationSet Name=""FK_Products_Suppliers"" Association=""NorthwindModel.FK_Products_Suppliers""><End Role=""Products"" EntitySet=""Products"" /><End Role=""Suppliers"" EntitySet=""Suppliers"" /></AssociationSet><AssociationSet Name=""FK_Territories_Region"" Association=""NorthwindModel.FK_Territories_Region""><End Role=""Region"" EntitySet=""Regions"" /><End Role=""Territories"" EntitySet=""Territories"" /></AssociationSet></EntityContainer></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0, ModelPart1, ModelPart2, ModelPart3, ModelPart4);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }

    [global::System.Data.Services.Common.EntitySetAttribute("Employees")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("EmployeeID")]
    public partial class Employee : global::System.ComponentModel.INotifyPropertyChanged
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Employee CreateEmployee(int employeeID, string lastName, string firstName)
        {
            Employee employee = new Employee();
            employee.EmployeeID = employeeID;
            employee.LastName = lastName;
            employee.FirstName = firstName;
            return employee;
        }       
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int EmployeeID
        {
            get
            {
                return this._EmployeeID;
            }
            set
            {
                this.OnEmployeeIDChanging(value);
                this._EmployeeID = value;
                this.OnEmployeeIDChanged();
                this.OnPropertyChanged("EmployeeID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _EmployeeID;
        partial void OnEmployeeIDChanging(int value);
        partial void OnEmployeeIDChanged();        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this._LastName = value;
                this.OnLastNameChanged();
                this.OnPropertyChanged("LastName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this._FirstName = value;
                this.OnFirstNameChanged();
                this.OnPropertyChanged("FirstName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string TitleOfCourtesy
        {
            get
            {
                return this._TitleOfCourtesy;
            }
            set
            {
                this.OnTitleOfCourtesyChanging(value);
                this._TitleOfCourtesy = value;
                this.OnTitleOfCourtesyChanged();
                this.OnPropertyChanged("TitleOfCourtesy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _TitleOfCourtesy;
        partial void OnTitleOfCourtesyChanging(string value);
        partial void OnTitleOfCourtesyChanged();

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> ReportsTo
        {
            get
            {
                return this._ReportsTo;
            }
            set
            {
                this.OnReportsToChanging(value);
                this._ReportsTo = value;
                this.OnReportsToChanged();
                this.OnPropertyChanged("ReportsTo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _ReportsTo;
        partial void OnReportsToChanging(global::System.Nullable<int> value);
        partial void OnReportsToChanged();       
          
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }

        }
    }
}
